// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt0evAmBaYzX42Druy2ai3W7Qos4zNkEM',
    appId: '1:56433400000:web:1a3ef9877436206dbcf525',
    messagingSenderId: '56433400000',
    projectId: 'gor-project-b3aba',
    authDomain: 'gor-project-b3aba.firebaseapp.com',
    storageBucket: 'gor-project-b3aba.appspot.com',
    measurementId: 'G-ZG2HRTYMLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3GhkrXlE-OiuwXtbcte37Y9AgJzr9StI',
    appId: '1:56433400000:android:17fc8ff5e5f5ccafbcf525',
    messagingSenderId: '56433400000',
    projectId: 'gor-project-b3aba',
    storageBucket: 'gor-project-b3aba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuGoli_gKWSOu7Vo0UWwidzbIu9JGs_ms',
    appId: '1:56433400000:ios:6299e1cfc47af6afbcf525',
    messagingSenderId: '56433400000',
    projectId: 'gor-project-b3aba',
    storageBucket: 'gor-project-b3aba.appspot.com',
    iosBundleId: 'com.example.gorProject',
  );
}
